User information updated.
SallaApp/oauth2-merchant pull request #19
Opened 2022-10-13 08:10 UTC by AtefR

Update user information to get domain, tax and commercial numbers.

Current [user information response](https://docs.salla.dev/docs/merchant/61d8f18097b4e-user-information):

```
{
  "status": 200,
  "success": true,
  "data": {
    "id": 1689171978,
    "name": "Test User",
    "email": "test@gmail.com",
    "mobile": "+966555555555",
    "role": "user",
    "created_at": "2021-03-27 21:51:56",
    "merchant": {
      "id": 847769313,
      "username": "User_name123",
      "name": "User Name",
      "avatar": "https://i.ibb.co/jyqRQfQ/avatar-male.webp",
      "store_location": "21.589481104199123,39.67869125586653",
      "plan": "pro",
      "status": "active",
      "domain": "https://www.domain.com",
      "tax_number": "424243241321234",
      "commercial_number": "3552100509",
      "created_at": "2021-12-31 12:59:59"
    }
  }
}
```

2023-07-11 06:13 UTC, salkhwlani requested changes

2023-07-11 06:13 UTC, salkhwlani commented on src/Provider/SallaUser.php
> +     * Get store status.
update the docs

2023-07-11 06:13 UTC, salkhwlani commented on src/Provider/SallaUser.php
> +        return $this->getResponseValue('data.merchant.tax_number');
i think this should be `commercial_number`

2023-07-11 06:13 UTC, salkhwlani commented on src/Provider/SallaUser.php
> +    public function getStoreDomain()
remove this, is already supported in the master

2023-07-20 07:48 UTC, HazemKhaled approved these changes

2023-07-20 07:48 UTC, HazemKhaled commented on src/Provider/SallaUser.php
> +     * Get store status.
```suggestion
     * Get store domain.
```

2023-10-01 09:32 UTC, salkhwlani approved these changes

2023-10-01 09:33 UTC, merged